# Generated by Django 5.0.4 on 2025-07-02 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_card_id",
                    models.CharField(
                        help_text="ID do PaymentMethod no Stripe",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        help_text="Marca do cartão (Visa, Mastercard, etc.)",
                        max_length=120,
                    ),
                ),
                (
                    "last_four_digits",
                    models.CharField(
                        help_text="Últimos 4 dígitos do cartão", max_length=4
                    ),
                ),
                ("exp_month", models.IntegerField(help_text="Mês de expiração")),
                ("exp_year", models.IntegerField(help_text="Ano de expiração")),
                (
                    "default",
                    models.BooleanField(
                        default=False, help_text="Cartão padrão para pagamentos"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "billing_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="billing.billingprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cartão Salvo",
                "verbose_name_plural": "Cartões Salvos",
                "ordering": ["-default", "-timestamp"],
            },
        ),
    ]
