# Generated by Django 5.0.4 on 2025-01-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="address_line_1",
        ),
        migrations.RemoveField(
            model_name="address",
            name="address_line_2",
        ),
        migrations.RemoveField(
            model_name="address",
            name="address_type",
        ),
        migrations.RemoveField(
            model_name="address",
            name="billing_profile",
        ),
        migrations.AddField(
            model_name="address",
            name="complement",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="street",
            field=models.CharField(default="Campo obrigatório", max_length=255),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(max_length=100),
        ),
    ]
