# Generated by Django 5.0.4 on 2025-01-20 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0002_remove_address_address_line_1_and_more"),
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                choices=[("billing", "Billing"), ("shipping", "Shipping")],
                default="shipping",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="billing_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="billing.billingprofile",
            ),
        ),
    ]
