# Generated by Django 5.0.4 on 2025-01-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0003_address_address_type_address_billing_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="complement",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="neighborhood",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="number",
            field=models.CharField(blank=True, default="", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(default="", max_length=255),
        ),
    ]
