# Generated by Django 5.0.4 on 2025-01-16 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["order", "timestamp"],
                "verbose_name": "Imagem do Produto",
                "verbose_name_plural": "Imagens do Produto",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Marque para definir como imagem principal do produto",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Ordem de exibição da imagem"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Texto alternativo para SEO e acessibilidade",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                help_text="Imagem do produto. Recomendado: 800x800px",
                upload_to="products/",
            ),
        ),
    ]
