# Generated by Django 5.0.4 on 2025-01-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
