# Generated by Django 5.0.4 on 2025-01-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_options_alter_productimage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
