# Generated by Django 5.0.4 on 2025-01-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_updated_productimage_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
