# Generated by Django 5.0.4 on 2025-01-17 00:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_productimage_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
